name: Releases

on:
  workflow_dispatch:

  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: "setup go"
      uses: actions/setup-go@v5
      with:
        cache: true
        go-version: '1.23'

    - name: build
      run: make zip

    - name: "create release"
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        artifacts: "release/*.zip"
        draft: true
        generateReleaseNotes: true
